# Generated by Django 5.1.3 on 2024-11-21 17:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Время обновление')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Фамилия')),
                ('email', models.EmailField(default='', help_text='Напишите свою почту', max_length=254, unique=True)),
                ('refresh_token', models.CharField(default=uuid.uuid4, max_length=255, unique=True, verbose_name='Обновляемый Токен для пользователя')),
                ('access_token', models.CharField(default=uuid.uuid4, max_length=255, unique=True, verbose_name='Токен для пользователя')),
                ('password', models.CharField(max_length=255, verbose_name='Пароль')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
            },
        ),
    ]
