# Generated by Django 5.1.3 on 2024-11-23 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Введите свой номер телефона в формате +77772221212', max_length=15, verbose_name='Номер телефона'),
        ),
    ]
