# Generated by Django 5.1.3 on 2024-12-01 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='is_confirmed',
            field=models.BooleanField(default=False, verbose_name='Подтвержден ли аккаунт'),
        ),
    ]
